title: Tāttvika Project
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
defaults:
  - scope:
      path: "README.md"
    values:
      nav_exclude: true
aux_links:
  "View on GitHub":
    - "https://github.com/ParthoM7/tattvika-project"      
